### ISSUE TITLE
Possible Crash

### ISSUE THREAD

**Issue by 1024jon** [jswetzen/ppstagedisplay#11]
This may be because of something on my PP system but, I left ppstagedisplay running for a few hours on the pi and when I came back it had crashed with this error.  I am testing it again now to see if it is repeatable.

Unknown message, how can this be?!
DisplayLayout
{ name: 'DisplayLayout',
  attributes:
   { showBorder: '1E0',
     width: '1440',
     identifier: 'Default copy',
     height: '900' },
  children:
   [ { name: 'Frame', attributes: [Object], children: [], content: '' },
     { name: 'Frame', attributes: [Object], children: [], content: '' },
     { name: 'Frame', attributes: [Object], children: [], content: '' },
     { name: 'Frame', attributes: [Object], children: [], content: '' },
     { name: 'Frame', attributes: [Object], children: [], content: '' },
     { name: 'Frame', attributes: [Object], children: [], content: '' } ],
  content: '' }
/home/pi/ppstagedisplay/lib/propresenter_communication.js:188
      switch (message.root.name) {
                          ^

TypeError: Cannot read property 'name' of undefined
    at handleData (/home/pi/ppstagedisplay/lib/propresenter_communication.js:188:27)
    at Socket.<anonymous> (/home/pi/ppstagedisplay/lib/reconnector.js:37:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)

**Comment by kevindoveton** [comment]
What version of propresenter is this?

**Comment by 1024jon** [comment]
5.3.3

**Comment by 1024jon** [comment]
Im thinking that the pi may have lost network connection, I was testing it on wifi.  When I drop it off the wifi I get this error.  I will keep testing it, but I think that is all it was.
