### ISSUE TITLE
Raspberry pi?

### ISSUE THREAD

**Issue by noneel** [jswetzen/ppstagedisplay#4]
Can you please write a tutorial for using this on a Raspberry Pi?

**Comment by jswetzen** [comment]
Yes, I've been planning to do so for quite a while. I don't know exactly when I'll get around to it, but meanwhile you might try the release. The raspberry love image is a bit old but I think it could run. The setup instructions are for Mac, and when you boot the Pi, the root password is either "raspberry" or "dietpi".
https://github.com/jswetzen/ppstagedisplay/releases

**Comment by noneel** [comment]
I've been working on it from Raspian but have had a lot of problems with Node.js, i'll give it a shot. Thank you so much for making this it!

**Comment by jswetzen** [comment]
You're welcome! Ask again if it doesn't work out. Maybe this issue can be material for a tutorial eventually.

**Comment by noneel** [comment]
Just an update I have gotten it working on Raspbian pretty simple, the hardest part was getting node.js and npm to run it, I got it working with: node version 0.10.29, npm version 1.4.21. I used raspian branch because I changed the code to execute a file called ~/runbrowser.sh after it connected. Then inside that ran http://localhost:9000 on a browser fullscreen.

```
sudo apt-get update && apt-get upgrade -y

sudo apt-get install git-core libnss-mdns libavahi-compat-libdnssd-dev npm -y

install your release or any other release ------ https://nodejs.org/en/blog/release/v0.10.29/

node -v
npm -v

git clone -b raspian-runbrowser https://github.com/natertot12/ppstagedisplay.git
cd ppstagedisplay

sudo npm install -g node-gyp
sudo npm install -g underscore
sudo npm install -g mdns

npm rebuild
npm install
```

Then of course just run it `node index.js`

**Comment by jswetzen** [comment]
Perfect! I can try the steps myself at some point and turn it into a wiki entry. Thanks a lot!
